# Generated by Django 4.0 on 2022-12-09 10:58

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='Banner/')),
                ('sub_heading', models.CharField(max_length=100)),
                ('main_heading', models.CharField(max_length=350)),
                ('short_description', models.CharField(max_length=350)),
            ],
        ),
    ]
