# Generated by Django 4.0 on 2022-12-09 11:08

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='Banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='short_description',
            field=models.CharField(max_length=3),
        ),
    ]
