# Generated by Django 4.0 on 2022-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_banner_image_alter_banner_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='short_description',
            field=models.CharField(max_length=350),
        ),
    ]
