# Generated by Django 4.0 on 2022-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_banner_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
