# Generated by Django 4.0 on 2022-12-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseEnquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
